<!-- Add CSS Variables -->
<style>
    :root {
        --body-color: #EE4266;

        --theme__color__primary: #EE4266;
        --theme__color__primary-alt: #FFD23F;
        --theme__color__secondary: #540D6E;

        --font-family: "Yuji Mai", sans-serif;
    }
</style>

<!-- Add Google Fonts -->
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Yuji+Mai:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap" rel="stylesheet">
